apiVersion: v1
kind: Secret
metadata:
  name: mapt-kind-secret
  namespace: mapt-operator-system
type: Opaque
stringData:
  access-key: "<access-key>"
  bucket: "<bucket>"
  region: "<region>"
  secret-key: "<secret-key>"
