---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mapt.redhat.com
  resources:
  - kinds
  - openshifts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mapt.redhat.com
  resources:
  - kinds/finalizers
  - openshifts/finalizers
  verbs:
  - update
- apiGroups:
  - mapt.redhat.com
  resources:
  - kinds/status
  - openshifts/status
  verbs:
  - get
  - patch
  - update
