apiVersion: mapt.redhat.com/v1alpha1
kind: Kind
metadata:
  name: kind-sample1
  labels:
    app.kubernetes.io/name: mapt-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  identifier: devcluster1

  cloudConfig:
    provider: AWS
    credentialsSecretRef:
      name: aws-creds-secret

  machineConfig:
    architecture: x86_64
    cpus: 8
    memoryGiB: 32
    nestedVirtualizationEnabled: false
    useSpotInstances: true
    spotPriceIncreasePercentage: 15
    tags:
      env: dev
      owner: team-x

  kindClusterConfig:
    kubernetesVersion: v1.29.2

  outputKubeconfigSecretName: kind-devcluster1-kubeconfig
  terminationPolicy:
    deleteAfterSeconds: 86400  # 1 day
