//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConfig) DeepCopyInto(out *CloudConfig) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConfig.
func (in *CloudConfig) DeepCopy() *CloudConfig {
	if in == nil {
		return nil
	}
	out := new(CloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kind) DeepCopyInto(out *Kind) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kind.
func (in *Kind) DeepCopy() *Kind {
	if in == nil {
		return nil
	}
	out := new(Kind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kind) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterConfig) DeepCopyInto(out *KindClusterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterConfig.
func (in *KindClusterConfig) DeepCopy() *KindClusterConfig {
	if in == nil {
		return nil
	}
	out := new(KindClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindList) DeepCopyInto(out *KindList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kind, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindList.
func (in *KindList) DeepCopy() *KindList {
	if in == nil {
		return nil
	}
	out := new(KindList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KindList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindSpec) DeepCopyInto(out *KindSpec) {
	*out = *in
	out.CloudConfig = in.CloudConfig
	in.MachineConfig.DeepCopyInto(&out.MachineConfig)
	out.KindClusterConfig = in.KindClusterConfig
	if in.TerminationPolicy != nil {
		in, out := &in.TerminationPolicy, &out.TerminationPolicy
		*out = new(TerminationPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindSpec.
func (in *KindSpec) DeepCopy() *KindSpec {
	if in == nil {
		return nil
	}
	out := new(KindSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindStatus) DeepCopyInto(out *KindStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AWSInstanceID != nil {
		in, out := &in.AWSInstanceID, &out.AWSInstanceID
		*out = new(string)
		**out = **in
	}
	if in.KubeconfigSecretName != nil {
		in, out := &in.KubeconfigSecretName, &out.KubeconfigSecretName
		*out = new(string)
		**out = **in
	}
	if in.KindVersion != nil {
		in, out := &in.KindVersion, &out.KindVersion
		*out = new(string)
		**out = **in
	}
	if in.ExpirationTimestamp != nil {
		in, out := &in.ExpirationTimestamp, &out.ExpirationTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ProvisionId != nil {
		in, out := &in.ProvisionId, &out.ProvisionId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindStatus.
func (in *KindStatus) DeepCopy() *KindStatus {
	if in == nil {
		return nil
	}
	out := new(KindStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfig) DeepCopyInto(out *MachineConfig) {
	*out = *in
	if in.SpotPriceIncreasePercentage != nil {
		in, out := &in.SpotPriceIncreasePercentage, &out.SpotPriceIncreasePercentage
		*out = new(int)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfig.
func (in *MachineConfig) DeepCopy() *MachineConfig {
	if in == nil {
		return nil
	}
	out := new(MachineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Openshift) DeepCopyInto(out *Openshift) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Openshift.
func (in *Openshift) DeepCopy() *Openshift {
	if in == nil {
		return nil
	}
	out := new(Openshift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Openshift) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftClusterConfig) DeepCopyInto(out *OpenshiftClusterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftClusterConfig.
func (in *OpenshiftClusterConfig) DeepCopy() *OpenshiftClusterConfig {
	if in == nil {
		return nil
	}
	out := new(OpenshiftClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftList) DeepCopyInto(out *OpenshiftList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Openshift, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftList.
func (in *OpenshiftList) DeepCopy() *OpenshiftList {
	if in == nil {
		return nil
	}
	out := new(OpenshiftList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenshiftList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftSpec) DeepCopyInto(out *OpenshiftSpec) {
	*out = *in
	out.OpenshiftClusterConfig = in.OpenshiftClusterConfig
	in.MachineConfig.DeepCopyInto(&out.MachineConfig)
	in.TerminationPolicy.DeepCopyInto(&out.TerminationPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftSpec.
func (in *OpenshiftSpec) DeepCopy() *OpenshiftSpec {
	if in == nil {
		return nil
	}
	out := new(OpenshiftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftStatus) DeepCopyInto(out *OpenshiftStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AWSInstanceID != nil {
		in, out := &in.AWSInstanceID, &out.AWSInstanceID
		*out = new(string)
		**out = **in
	}
	if in.KubeconfigSecretName != nil {
		in, out := &in.KubeconfigSecretName, &out.KubeconfigSecretName
		*out = new(string)
		**out = **in
	}
	if in.ProvisionStartTime != nil {
		in, out := &in.ProvisionStartTime, &out.ProvisionStartTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.ExpirationTimestamp != nil {
		in, out := &in.ExpirationTimestamp, &out.ExpirationTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ProvisionId != nil {
		in, out := &in.ProvisionId, &out.ProvisionId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftStatus.
func (in *OpenshiftStatus) DeepCopy() *OpenshiftStatus {
	if in == nil {
		return nil
	}
	out := new(OpenshiftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminationPolicy) DeepCopyInto(out *TerminationPolicy) {
	*out = *in
	if in.DeleteAfterSeconds != nil {
		in, out := &in.DeleteAfterSeconds, &out.DeleteAfterSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminationPolicy.
func (in *TerminationPolicy) DeepCopy() *TerminationPolicy {
	if in == nil {
		return nil
	}
	out := new(TerminationPolicy)
	in.DeepCopyInto(out)
	return out
}
